version: "3.9"
services:
    postgres:
      image: postgres:9.6-alpine
      ports:
        - 5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrepass
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

    dev-app:
        build: .
        entrypoint: npm run dev
        ports:
            - "3000:3000"
            - "9229:9229"
        environment: 
            - PORT=3000
            - DB_HOST='postgres'
            - DB_PORT='5432'
            - DB_NAME=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
        volumes: 
            - .:/dev-app
            - /dev-app/node_modules
        depends_on:
            - postgres    
        links:
            - postgres