version: "3.9"
services:
    postgres:
      build:
        context: .
        dockerfile: Dockerfile.database
        args:
          - USER_ID=${USER_ID}
          - GROUP_ID=${GROUP_ID}
      ports:
        - 5432
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgrepass
      volumes:
        - ./postgres-data/:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

    dev-app:
      build:
        context: .
        dockerfile: Dockerfile
      entrypoint: npm run dev
      ports:
          - 3000:3000
          - 9229:9229
      environment:
          - PORT=3000
          - DB_HOST=postgres
          - DB_PORT=5432
          - DB_NAME=postgres
          - DB_USERNAME=postgres
          - DB_PASSWORD=postgrepass
      volumes:
          - .:/dev-app
          - /dev-app/node_modules
      depends_on:
          - postgres
      links:
          - postgres
